### ISSUE TITLE
Error on running AnalysisLauncher

### ISSUE THREAD

**Issue by dlogan** [lhilbert/ivma3#1]
First - thanks for this!  I'm trying this out on an AVI and it's erroroing:

```
>> AnalysisLauncher
Call to analysis function...
Analysis completed, computation time 0.764320 seconds

Error:Undefined function 'read' for input arguments of type 'double'., in
[My filename]
```

Any thoughts on this?  Are there specs on the types of AVI or rather, underlying image filetypes, that might be causing this read error?  But 'read' is not defined...

I'm using matlab 2016a.

**Comment by dlogan** [comment]
P.S. This also occurs for the Example Videos from this repo, so it's not anything specific to my videos:
```
>> AnalysisLauncher
Call to analysis function...
Analysis completed, computation time 16.026783 seconds

Error:Undefined function 'read' for input arguments of type 'double'., in
[OUTPUT_PATH]\Example_output_DLogan\Slide3\20111007184150671


Error:Undefined function 'read' for input arguments of type 'double'., in
[OUTPUT_PATH]\Slide3\20111007184219234
...
```

**Comment by lhilbert** [comment]
Thanks for the error report.

On first glance it looks like a problem with the avi read functions,
potentially version related. MathWorks keeps changing these all the time.

I'll get to it once I find an hour or two...

Lennart

**Comment by lhilbert** [comment]
Alright, it looks like the read() method of the VideoReader object has been quietly removed. This object seems to change from version to version, which doesn't help for code stability...

It should work now, if not please let me know again!

**Comment by dlogan** [comment]
Thanks for looking into this, but I don't see any code changed.  Maybe you just need to push to the repo?

**Comment by lhilbert** [comment]
Yes, did that. I can see the updated code now. Is it working?

**Comment by dlogan** [comment]
Yes, that works now.  And it seems to be processing at least your Example Videos.  Thanks!

**Comment by lhilbert** [comment]
Let me know if you find anything else or have questions, please.

Hope the scripts can help you!

Lennart
